### ISSUE TITLE
AttributeError: 'FD' object has no attribute 'sd_gran'

### ISSUE THREAD

**Issue by Zeyu-ZEYU** [UMass-LIDS/Tragen#1]
I was trying to run GUI in this way down below.

![image](https://user-images.githubusercontent.com/9370822/155215044-5cffaf7a-2727-4721-a712-d30cb9946e54.png)

But an error was raised.

```
Done!
Computing the traffic model for the traffic mix
/Code/Tragen/FDUtils.py:103: ComplexWarning: Casting complex values to real discards the imaginary part
  st12[t][out_k[i]] = float(st12_conv[i]) * prob_t12[0]
Computing the traffic model for the traffic mix
Traceback (most recent call last):
  File "/Code/Tragen/tragen_gui.py", line 30, in run
    self.trafficMixer    = TrafficMixer(self.args, self.printBox)
  File "/Code/Tragen/traffic_mixer.py", line 49, in __init__
    self.mix()
  File "/Code/Tragen/traffic_mixer.py", line 94, in mix
    fd_prev_iter.addition(self.FDs[i+1], fd_new, self.args.hitrate_type)
  File "/Code/Tragen/fd.py", line 60, in addition
    self.fd_util.convolve_2d_fft(self.st, fd2.st, fd_res.st, rate1, rate2, self.sd_gran)
AttributeError: 'FD' object has no attribute 'sd_gran'
zsh: abort      /usr/bin/env python3
```

**Comment by anisabnis** [comment]
Thanks for pointing this out.

I have fixed the code and pushed it to the repository. Please let me know if it still throws an error.

**Comment by anisabnis** [comment]
Closing issue.
